### ISSUE TITLE
Missing dns entry

### ISSUE THREAD

**Issue by tojosephyang** [openshift/hive#1164]
I am trying to create a cluster in AWS with following configuration yaml:
```
apiVersion: v1
items:
- apiVersion: hive.openshift.io/v1
  kind: ClusterDeployment
  metadata:
    creationTimestamp: null
    labels:
      hive.openshift.io/hiveutil-created: "true"
    name: mycluster
  spec:
    baseDomain: purple-ontario.com
    clusterName: mycluster1
    controlPlaneConfig:
      servingCertificates: {}
    installed: false
    platform:
      aws:
        credentialsSecretRef:
          name: mycluster-aws-creds
        region: us-east-1
    provisioning:
      imageSetRef:
        name: mycluster-imageset
      installConfigSecretRef:
        name: mycluster-install-config
  status: {}
- apiVersion: hive.openshift.io/v1
  kind: MachinePool
  metadata:
    creationTimestamp: null
    name: mycluster-worker
  spec:
    clusterDeploymentRef:
      name: mycluster
    name: worker
    platform:
      aws:
        rootVolume:
          iops: 100
          size: 22
          type: gp2
        type: m5.2xlarge
    replicas: 3
  status: {}
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: mycluster-install-config
  stringData:
    install-config.yaml: |
      apiVersion: v1
      baseDomain: purple-ontario.com
      compute:
      - name: worker
        platform:
          aws:
            rootVolume:
              iops: 100
              size: 22
              type: gp2
            type: m5.xlarge
        replicas: 3
      controlPlane:
        name: master
        platform:
          aws:
            rootVolume:
              iops: 100
              size: 22
              type: gp2
            type: m4.xlarge
        replicas: 3
      metadata:
        creationTimestamp: null
        name: mycluster
      networking:
        clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
        machineNetwork:
        - cidr: 10.0.0.0/16
        networkType: OpenShiftSDN
        serviceNetwork:
        - 172.30.0.0/16
      platform:
        aws:
          region: us-east-1
      pullSecret: ""
      sshKey: "data"
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: mycluster-aws-creds
  stringData:
    aws_access_key_id: "data"
    aws_secret_access_key: "data"
  type: Opaque
- apiVersion: hive.openshift.io/v1
  kind: ClusterImageSet
  metadata:
    creationTimestamp: null
    name: mycluster-imageset
  spec:
    releaseImage: quay.io/openshift-release-dev/ocp-release:4.6.0-fc.8-x86_64
  status: {}
kind: List
metadata: {}
```
The provision process fails in 
```

time="2020-10-07T00:57:34Z" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.11: 13% complete"
time="2020-10-07T00:57:49Z" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.5.11: 86% complete"
time="2020-10-07T01:00:34Z" level=debug msg="Still waiting for the cluster to initialize: Cluster operator console is reporting a failure: RouteHealthDegraded: failed to GET route (https://console-openshift-console.apps.mycluster.purple-ontario.com/health): Get https://console-openshift-console.apps.mycluster.purple-ontario.com/health: dial tcp: lookup console-openshift-console.apps.mycluster.purple-ontario.com on 172.30.0.10:53: no such host"
time="2020-10-07T01:17:02Z" level=error msg="Cluster operator authentication Degraded is True with RouteHealth_FailedGet: RouteHealthDegraded: failed to GET route: dial tcp: lookup oauth-openshift.apps.mycluster.purple-ontario.com on 172.30.0.10:53: no such host"
time="2020-10-07T01:17:02Z" level=info msg="Cluster operator authentication Progressing is Unknown with NoData: "
time="2020-10-07T01:17:02Z" level=info msg="Cluster operator authentication Available is Unknown with NoData: "
time="2020-10-07T01:17:02Z" level=error msg="Cluster operator console Degraded is True with RouteHealth_FailedGet: RouteHealthDegraded: failed to GET route (https://console-openshift-console.apps.mycluster.purple-ontario.com/health): Get https://console-openshift-console.apps.mycluster.purple-ontario.com/health: dial tcp: lookup console-openshift-console.apps.mycluster.purple-ontario.com on 172.30.0.10:53: no such host"
time="2020-10-07T01:17:02Z" level=info msg="Cluster operator console Progressing is True with SyncLoopRefresh_InProgress: SyncLoopRefreshProgressing: Working toward version 4.5.11"
time="2020-10-07T01:17:02Z" level=info msg="Cluster operator console Available is False with Deployment_InsufficientReplicas: DeploymentAvailable: 0 pods available for console deployment"
time="2020-10-07T01:17:02Z" level=info msg="Cluster operator insights Disabled is False with : "
time="2020-10-07T01:17:02Z" level=fatal msg="failed to initialize the cluster: Cluster operator console is reporting a failure: RouteHealthDegraded: failed to GET route (https://console-openshift-console.apps.mycluster.purple-ontario.com/health): Get https://console-openshift-console.apps.mycluster.purple-ontario.com/health: dial tcp: lookup console-openshift-console.apps.mycluster.purple-ontario.com on 172.30.0.10:53: no such host"
time="2020-10-07T01:17:03Z" level=error msg="error after waiting for command completion" error="exit status 1" installID=5sst9tqc
time="2020-10-07T01:17:03Z" level=error msg="error provisioning cluster" error="exit status 1" installID=5sst9tqc
time="2020-10-07T01:17:03Z" level=error msg="error running openshift-install, running deprovision to clean up" error="exit status 1" installID=5sst9tqc
time="2020-10-07T01:17:03Z" level=debug msg="OpenShift Installer v4.5.0"
time="2020-10-07T01:17:03Z" level=debug msg="Built from commit 310205b3cee9e166544b882e8ea8b321af198b6f"
time="2020-10-07T01:17:03Z" level=info msg="Waiting up to 20m0s for the Kubernetes API at https://api.mycluster.purple-ontario.com:6443..."
time="2020-10-07T01:17:03Z" level=info msg="API v1.18.3+b0068a8 up"
time="2020-10-07T01:17:03Z" level=info msg="Waiting up to 40m0s for bootstrapping to complete..."
time="2020-10-07T01:17:03Z" level=debug msg="Bootstrap status: complete"
time="2020-10-07T01:17:03Z" level=info msg="It is now safe to remove the bootstrap resources"
time="2020-10-07T01:17:03Z" level=info msg="Time elapsed: 0s"
time="2020-10-07T01:17:03Z" level=info msg="attempting to gather logs with oc adm must-gather" installID=5sst9tqc
time="2020-10-07T01:21:40Z" level=info msg="must-gather output: [must-gather      ] OUT Using must-gather plugin-in image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b8ff8903dccf7a57f12e4e19d000012d64cbada7a30610abaf9e7e89086ac4a3\n[must-gather      ] OUT namespace/op
```
Compared AWS route53 records created by this cluster with other created by openshift-installer, found the subdomain mycluster.purple-ontario.com is missing a record *.app.mycluster.purple-ontario.com. Maybe that is why the installer can not find https://console-openshift-console.apps.mycluster.purple-ontario.com/health. 

I have tried different versions of OCP, 4.5.15. 4.6.0-fc and 4.5.11, they are all the same errors. 

Can someone help to clarify what else is missing here?
--
