### ISSUE TITLE
How to recover a cluster "FailedToStart"?

### ISSUE THREAD

**Issue by tojosephyang** [openshift/hive#1206]
There is a clusterclaim marked as "FailedToStart".
```
  conditions:
  - lastProbeTime: "2020-11-11T00:02:39Z"
    lastTransitionTime: "2020-11-11T00:00:05Z"
    message: "Failed to start machines: IncorrectInstanceState: The instance 'i-0af38ae20ac9715a7' is not in a state from which it can be started.\n\tstatus code: 400, request id: ada05e60-b2fe-4dbd-a7d1-824c19861d95"
    reason: FailedToStart
    status: "True"
    type: Hibernating
```
I tried to change its .spec.powerState to Hibernate/Running by "oc edit". Nothing changed. I can bring the cluster back by starting the cluster node EC2 in AWS console; however, changing .spec.powerState does not work any more to switch it to hibernate. 
Is there a way to recover this cluster back to normal?
