### ISSUE TITLE
MachinePool not creating corresponding MachineSets on Openstack

### ISSUE THREAD

**Issue by usamaahmadkhan** [openshift/hive#1228]
Trying to create MachinePools for clusters on openstack. MachinePools are created successfully, but the reconcile outcome is `unspecified` and the expected MachineSet is not created. The status section of the MachinePool CR is also empty.
```
time="2020-12-09T13:43:58.184Z" level=info msg="reconciling machine pool" controller=remotemachineset machinePool=cluster-stakater-binero/openshift-binero-infra reconcileID=qlswj9bj
time="2020-12-09T13:43:58.504Z" level=info msg="reconciling machine pool for cluster deployment" controller=remotemachineset machinePool=cluster-stakater-binero/openshift-binero-infra reconcileID=qlswj9bj
time="2020-12-09T13:43:58.582Z" level=info msg="found 2 remote machine sets" controller=remotemachineset machinePool=cluster-stakater-binero/openshift-binero-infra reconcileID=qlswj9bj
time="2020-12-09T13:43:58.582Z" level=info msg="reconcile complete" controller=remotemachineset elapsedMillis=398 elapsedMillisGT=0 machinePool=cluster-stakater-binero/openshift-binero-infra outcome=unspecified reconcileID=qlswj9bj
```
MachinePool:
```
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: openshift-binero-infra
  namespace: cluster-stakater-binero
spec:
  clusterDeploymentRef:
    name: openshift-binero
  resourceApplyMode: Sync
  name: infra
  labels:
    machine.openshift.io/cluster-api-machine-role: infra
    machine.openshift.io/cluster-api-machine-type: infra
    node-role.kubernetes.io/infra: "" 
  platform:
    openstack:
      flavor: hp.8x32
      rootVolume:
        size: 100
        type: ssd
      zones:
      - europe-se-1a
  replicas: 3
```
