### ISSUE TITLE
Ability to Override httpCustomErrorCodePages in ClusterDeployment

### ISSUE THREAD

**Issue by John2020-cyber** [openshift/hive#1889]
I have a Custom ConfigMap for HTTP error pages which I want to use on Spokes the cluster deployment creates the following syncset for ingresscontroller. 
```
apiVersion: hive.openshift.io/v1
kind: SyncSet
metadata:
  name: stakater-devtest-clusteringress
  namespace: stakater-devtest
  ownerReferences:
    - apiVersion: hive.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: ClusterDeployment
      name: stakater-devtest
      uid: 8572daee-a49c-4ebd-bc55-61e110b0a0b9
  labels:
    hive.openshift.io/cluster-deployment-name: stakater-devtest
    hive.openshift.io/syncset-type: remoteingress
spec:
  clusterDeploymentRefs:
    - name: stakater-devtest
  resourceApplyMode: Sync
  resources:
    - apiVersion: operator.openshift.io/v1
      kind: IngressController
      metadata:
        name: default
        namespace: openshift-ingress-operator
      spec:
        clientTLS:
          clientCA:
            name: ''
          clientCertificatePolicy: ''
        defaultCertificate:
          name: stakater-devtest-serving-cert-secret-generated
        domain: apps.devtest.*******.cloud
        httpCompression: {}
        httpErrorCodePages:
          name: ''
        tuningOptions: {}
      status:
        availableReplicas: 0
        domain: ''
        selector: ''
  secretMappings:
    - sourceRef:
        name: serving-cert-secret-generated
        namespace: stakater-devtest
      targetRef:
        name: stakater-devtest-serving-cert-secret-generated
        namespace: openshift-ingress
```
If I apply the following Patch to the Spoke directly the field  httpErrorCodePages.name is overwritten by the SyncSet owned by ClusterDeployment:
```
kind: SelectorSyncSet
apiVersion: hive.openshift.io/v1
metadata:
  name: default-ingress-controller-patch
spec:
  resourceApplyMode: Sync
  clusterDeploymentSelector:
    matchLabels:
      provider: stakater
      patchRouter: "true"
  patches:
    - kind: IngressController
      apiVersion: operator.openshift.io/v1
      name: default
      namespace: openshift-ingress-operator
      patch: |-
        spec:
          replicas: 3
          nodePlacement:
            nodeSelector:
              matchLabels:
                node-role.kubernetes.io/infra: ""
          logging:
            access:
              destination:
                type: Container
          httpErrorCodePages:
            name: saap-error-pages
      patchType: merge
```
Therefore cannot Edit Custom HTTP Pages on spokes
