### ISSUE TITLE
Limit number of NAT Gateways Created

### ISSUE THREAD

**Issue by faangbait** [openshift/hive#2466]
Not sure if this is simply missing documentation or a feature request.

We're using the following configuration to deploy SNO clusters via hive.

```yaml
    platform:
      aws:
        region: us-east-1
        zones:
          - us-east-1a
          - us-east-1b
```

I'd expect this to result in subnets/NAT Gateways to be created in just `us-east-1a` and `us-east-1b`, but the installer is creating gateways in `1c` through `1f` as well. 

Since the Openshift Installer defines this as an acceptable configuration parameter, I'm assuming the issue lies in hive; but I'm happy to repost this to the installer repository if developers here can confirm that is a better place for it.

**Comment by 2uasimojo** [comment]
Those gateways are definitely created by installer. I recall a discussion around this related to cost, where the crux was that you can save money by deploying smaller clusters into “smaller” regions (those with fewer AZs) since these gateways are always created and they’re expensive. But I don’t know if the topic was ever approached from the perspective of being able to restrict day 0 to just using the AZs in the install-config. 

Definitely something the installer team would need to answer. @patrickdillon ?

**Comment by patrickdillon** [comment]
This logic is definitely the responsibility of the installer side--not Hive. @faangbait feel free to open a bug against the installer. I have asked @mtulio to assess as well.

Also note  the config you posted is not valid. We don't have any section in the install config where `region` and `zones` are at the same level. I think the intent here was:

```yaml
    platform:
      aws:
        region: us-east-1
        defaultMachinePlatform:
          zones:
            - us-east-1a
            - us-east-1b
```
But AFAICT correcting the config still does not fix the issue, so I suspect we do need some changes in the installer logic.
