### ISSUE TITLE
Cannot have htpasswd secret created in provisioning cluster

### ISSUE THREAD

**Issue by clyang82** [openshift/hive#599]
I have followed [this guide](https://github.com/openshift/hive/blob/master/docs/syncidentityprovider.md) to create syncidentityprovider, but the htpasswd secret cannot be created in target cluster. Here is my syncidentityprovider file content:
```
---
apiVersion: hive.openshift.io/v1alpha1
kind: SyncIdentityProvider
metadata:
  name: allowall-identity-provider
spec:
  identityProviders:
  - name: htpasswd
    challenge: true
    login: true
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpasswd-zzl2r
  clusterDeploymentRefs:
  - name: "mycluster"
```

Am I missed anything? I just tried to create htpasswd-zzl2r secret in openshift-config namespace, everything is working now. Thanks.
