### ISSUE TITLE
Encountered "SignatureDoesNotMatch" when provisioning cluster on aws

### ISSUE THREAD

**Issue by xjtustt** [openshift/hive#635]
Detail of my env is as below:
os: macOS
minishift version: `v1.34.1+c2ff9cb`

My generated ClusterDeployment yaml file as below:
```
apiVersion: v1
items:
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: mycluster-abc-aws-creds
  stringData:
    aws_access_key_id: <my-access-key-id>
    aws_secret_access_key: <my-secret-access-key>
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: mycluster-abc-ssh-key
  stringData:
    ssh-privatekey: ""
    ssh-publickey: ssh-rsa xx
      “xx@example.com”
  type: Opaque
- apiVersion: hive.openshift.io/v1alpha1
  kind: ClusterDeployment
  metadata:
    creationTimestamp: null
    name: mycluster-abc
  spec:
    baseDomain: <my-base-domain>
    clusterName: mycluster-abc
    compute:
    - name: worker
      platform:
        aws:
          rootVolume:
            iops: 100
            size: 22
            type: gp2
          type: m4.large
      replicas: 3
    controlPlane:
      name: master
      platform:
        aws:
          rootVolume:
            iops: 100
            size: 22
            type: gp2
          type: m4.large
      replicas: 3
    controlPlaneConfig:
      servingCertificates: {}
    images:
      installerImagePullPolicy: Always
      releaseImage: quay.io/openshift-release-dev/ocp-release:4.2.0
    installed: false
    networking:
      clusterNetworks:
      - cidr: 10.128.0.0/14
        hostSubnetLength: 23
      machineCIDR: 10.0.0.0/16
      serviceCIDR: 172.30.0.0/16
      type: OpenShiftSDN
    platform:
      aws:
        region: us-east-2
    platformSecrets:
      aws:
        credentials:
          name: mycluster-abc-aws-creds
    sshKey:
      name: mycluster-abc-ssh-key
  status:
    adminKubeconfigSecret: {}
    adminPasswordSecret: {}
    clusterVersionStatus:
      availableUpdates: null
      desired:
        force: false
        image: ""
        version: ""
      observedGeneration: 0
      versionHash: ""
    installed: false
kind: List
metadata: {}
```

After I run `oc apply` to provision cluster, I got an error that shows:
```
time="2019-10-22T18:25:16Z" level=fatal msg="failed to fetch Master Machines: failed to fetch dependency of \"Master Machines\": failed to generate asset \"Platform Credentials Check\": validate AWS credentials: checking install permissions: error gathering AWS credentials details: error querying username: SignatureDoesNotMatch: Signature expired: 20191022T182514Z is now earlier than 20191023T091212Z (20191023T092712Z - 15 min.)\n\tstatus code: 403, request id: 152cfedd-b772-4764-bd02-7560256addc7"
time="2019-10-22T18:25:17Z" level=error msg="error after waiting for command completion" error="exit status 1" installID=s98lr622
time="2019-10-22T18:25:17Z" level=error msg="error generating installer assets" error="exit status 1" installID=s98lr622
time="2019-10-22T18:25:17Z" level=info msg="reading installer log" installID=s98lr622
time="2019-10-22T18:25:17Z" level=info msg="saving installer output" installID=s98lr622
time="2019-10-22T18:25:17Z" level=debug msg="installer console log: level=fatal msg=\"failed to fetch Master Machines: failed to fetch dependency of \\\"Master Machines\\\": failed to generate asset \\\"Platform Credentials Check\\\": validate AWS credentials: checking install permissions: error gathering AWS credentials details: error querying username: SignatureDoesNotMatch: Signature expired: 20191022T182514Z is now earlier than 20191023T091212Z (20191023T092712Z - 15 min.)\\n\\tstatus code: 403, request id: 152cfedd-b772-4764-bd02-7560256addc7\"\n" installID=s98lr622
time="2019-10-22T18:25:17Z" level=info msg="updating clusterprovision" installID=s98lr622
time="2019-10-22T18:25:17Z" level=fatal msg="runtime error" error="exit status 1"
```

My AWS credential is correct since I can use it to provision cluster through openshift-installer directly.
