### ISSUE TITLE
Cluster provision fails on missing cluster-config configmap

### ISSUE THREAD

**Issue by tzvatot** [openshift/hive#71]
During provision of cluster using hive we get the network-operator pod on error config:
```
[core@ip-10-0-3-26 ~]$ sudo oc get pods --config=/var/opt/tectonic/auth/kubeconfig --all-namespaces 
NAMESPACE                              NAME                                                              READY     STATUS                       RESTARTS   AGE
kube-system                            etcd-member-ip-10-0-8-201.ec2.internal                            1/1       Running                      0          1h
kube-system                            kube-proxy-n64xx                                                  1/1       Running                      0          1h
kube-system                            kube-scheduler-mjsc9                                              0/1       ContainerCreating            0          1h
kube-system                            tectonic-network-operator-gjps2                                   1/1       Running                      0          1h
openshift-cluster-api                  machine-api-operator-649c446d5b-49rf9                             0/1       Pending                      0          1h
openshift-cluster-dns-operator         cluster-dns-operator-6b8b9cbbcd-rmhsx                             0/1       Pending                      0          1h
openshift-cluster-network-operator     cluster-network-operator-cz466                                    0/1       CreateContainerConfigError   0          1h
openshift-cluster-version              cluster-version-operator-4lkmd                                    1/1       Running                      0          1h
openshift-core-operators               openshift-cluster-kube-apiserver-operator-576768b698-7mwg9        0/1       Pending                      0          1h
openshift-core-operators               openshift-cluster-kube-controller-manager-operator-76c57b55sgf8   0/1       Pending                      0          1h
openshift-core-operators               openshift-cluster-kube-scheduler-operator-5b6c66dd59-cc9nr        0/1       Pending                      0          1h
openshift-core-operators               openshift-cluster-openshift-apiserver-operator-759fd945d8-gw8tl   0/1       Pending                      0          1h
openshift-core-operators               openshift-cluster-openshift-controller-manager-operator-58prxwq   0/1       Pending                      0          1h
openshift-core-operators               openshift-service-cert-signer-operator-7fd688bd7f-rjft5           0/1       Pending                      0          1h
openshift-machine-config-operator      machine-config-operator-744f64d9c7-lrhtk                          0/1       Pending                      0          1h
openshift-operator-lifecycle-manager   catalog-operator-cf4cd9c5c-hhc9h                                  0/1       Pending                      0          1h
openshift-operator-lifecycle-manager   olm-operator-7f44dd6495-fv2wg                                     0/1       Pending                      0          1h
openshift-operator-lifecycle-manager   package-server-54d99f7dfc-s2jbq                                   0/1       Pending                      0          1h
```
Running `sudo oc get -o yaml pod -n openshift-cluster-network-operator cluster-network-operator-cz466 --config=/var/opt/tectonic/auth/kubeconfig` outputs that the pod is waiting for cluster-config configmap:
```
containerStatuses:
  - image: registry.svc.ci.openshift.org/openshift/origin-v4.0-20181107015454@sha256:af8333760046cefb84d5f222a96e28c8af06823de8e2fed44647d614cedc925a
    imageID: ""
    lastState: {}
    name: cluster-network-operator
    ready: false
    restartCount: 0
    state:
      waiting:
        message: configmaps "cluster-config" not found
        reason: CreateContainerConfigError
```
