### ISSUE TITLE
ClusterDeployment Spec Error with provided documented examples

### ISSUE THREAD

**Issue by slopezz** [openshift/hive#780]
Hi, I'm testing hive to manage a fleet of openshift clusters, and I have problems to create specific ClusterDeployments using provided documented examples from:
https://github.com/openshift/hive/blob/v1/config/templates/cluster-deployment.yaml
https://github.com/openshift/hive/blob/v1/config/samples/hive_v1_clusterdeployment.yaml
https://github.com/openshift/hive/blob/v1/docs/using-hive.md#provisioning

For example, when using the template which creates 3 `Secrets` plus the `ClusterDeployment` objects, I got the error:
```
    error: admission webhook "clusterdeploymentvalidators.admission.hive.openshift.io" denied the request: ClusterDeployment.hive.openshift.io "" is invalid: [spec.provisioning: Required value: provisioning is required if not installed, spec.platform.aws.credentialsSecretRef.name: Required value: must specify secrets for AWS access]
```

When using specific `ClusterDeployment` file like the following (after having successfully created aws-creds, pull-secret and ssh-key `Secrets`):

```
$ cat ClusterDeployment.yaml
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: hive-test
  namespace: hive
spec:
  platformSecrets:
    aws:
      credentials:
        name: aws-creds-examle
  imageSet:
    name: "openshift-v4.2.0"
  sshKey:
    name: ssh-key-example
  clusterName: hive-test
  baseDomain: example.net
  networking:
    type: OpenShiftSDN
    serviceCIDR: "172.30.0.0/16"
    machineCIDR: "10.0.0.0/16"
    clusterNetworks:
      - cidr: "10.128.0.0/14"
        hostSubnetLength: 23
  platform:
    aws:
      region: us-east-1
  pullSecret:
    name: pull-secret-example
  controlPlane:
    name: master
    replicas: 3
    platform:
      aws:
        type: m4.large
        rootVolume:
          size: 50
          type: gp2
  compute:
  - name: worker
    replicas: 3
    platform:
      aws:
        type: m4.large
        rootVolume:
          size: 50
          type: gp2
```
I get same errors:
```
$ oc apply -f ClusterDeployment.yaml
The ClusterDeployment "" is invalid: 
* spec.provisioning: Required value: provisioning is required if not installed
* spec.platform.aws.credentialsSecretRef.name: Required value: must specify secrets for AWS access
```

It seems that `ClusterDeployment` spec have changed from the ones documented on different examples through the repository (at least regarding aws creds secret ref...).

In addition, although I'm not getting any error with that, I've seen that the official opensift-installer service network field name differs from the one on hive `ClusterDeployment` (`serviceNetwork` vs `serviceCIDR`, I don't know if its intentioned or both are compatible).

I have successfully fixed myself the error with  `spec.platform.aws.credentialsSecretRef.name` (by setting the new supposed expected field tree, easy one), however I am still having the error with `spec.provisioning`, because I don't understand why `provisioning.installConfigSecretRef` is a required value (AFAIK, it contains cluster base64 install-config.yaml, so the same content already specified on ClusterDeployment spec).

I'm using hive operator image `registry.svc.ci.openshift.org/openshift/hivev1:hive` which I think is the last one from `master` branch.

Can you please check if documented examples of `ClusterDeployment` spec are wrong? Or if maybe I am doing something wrong?

**Comment by dgoodwin** [comment]
Hey Sergio, apologies for the delay responding, and for this problem. I think what has happened here is you are using the Hive v1 branch, which is the default right now, but the docs have not been updated and are still using v1alpha1. The templates, and samples are all probably somewhat off as well.

We will try to get these updated as soon as possible (I will add a Jira), we're going through the very tricky upgrade of our live environments from v1alpha1 to v1 in the next couple weeks. Trying to find someone to update these asap.

My recommendation would be to "make hiveutil", and use bin/hiveutil create-cluster with -o yaml to see what the latest output should look like, but we'll try to get docs updated very soon, possibly today.

**Comment by slopezz** [comment]
Hi @dgoodwin, thanks for the quick response. I already tried the `bin/hiveutil` tool to check which were the required files:
```
slopez @ ~/go/src/github.com/openshift/hive $ bin/hiveutil create-cluster --base-domain=mydomain.example.com --cloud=aws mycluster -o yaml

apiVersion: v1
items:
- apiVersion: hive.openshift.io/v1
  kind: ClusterImageSet
  metadata:
    creationTimestamp: null
    name: mycluster-imageset
  spec:
    releaseImage: quay.io/openshift-release-dev/ocp-release:4.3.0-x86_64
  status: {}
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    name: mycluster-aws-creds
  stringData:
    aws_access_key_id: A...Q
    aws_secret_access_key: 9...K
  type: Opaque
- apiVersion: v1
  data:
    install-config.yaml: Y...g==
  kind: Secret
  metadata:
    creationTimestamp: null
    name: mycluster-install-config
  type: Opaque
- apiVersion: hive.openshift.io/v1
  kind: ClusterDeployment
  metadata:
    creationTimestamp: null
    name: mycluster
  spec:
    baseDomain: mydomain.example.com
    clusterName: mycluster
    controlPlaneConfig:
      servingCertificates: {}
    installed: false
    platform:
      aws:
        credentialsSecretRef:
          name: mycluster-aws-creds
        region: us-east-1
    provisioning:
      imageSetRef:
        name: mycluster-imageset
      installConfigSecretRef:
        name: mycluster-install-config
  status:
    clusterVersionStatus:
      availableUpdates: null
      desired:
        force: false
        image: ""
        version: ""
      observedGeneration: 0
      versionHash: ""
- apiVersion: hive.openshift.io/v1
  kind: MachinePool
  metadata:
    creationTimestamp: null
    name: mycluster-worker
  spec:
    clusterDeploymentRef:
      name: mycluster
    name: worker
    platform:
      aws:
        rootVolume:
          iops: 100
          size: 22
          type: gp2
        type: m4.xlarge
    replicas: 3
  status:
    replicas: 0
kind: List
metadata: {}
```

Then I inspect what is inside the base64 `install-config.yaml`:
```
`install-config.yaml`
$ echo "Y....g==" | base64 --decode
apiVersion: v1
baseDomain: mydomain.example.com
compute:
- name: worker
  platform:
    aws:
      rootVolume:
        iops: 100
        size: 22
        type: gp2
      type: m4.xlarge
  replicas: 3
controlPlane:
  name: master
  platform:
    aws:
      rootVolume:
        iops: 100
        size: 22
        type: gp2
      type: m4.xlarge
  replicas: 3
metadata:
  creationTimestamp: null
  name: mycluster
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
pullSecret: ""
sshKey: ssh-rsa AA...bw==
  slopez@localhost.localdomain
```

However:
* I didn't understand why it is needed to embed base64 `install-config.yaml` (with pull secret, ssh-key. base domain, instances spec..) when for example instances spec is already defined on `ClusterDeployment` object making it redundant?
* In addition, according to docs I thought it was possible to not use independent `ClusterImageSet` or `MachinePool` objects, and embed their configuration directly on `ClusterDeployment` object (so everything regarding cluster spec on a single file definition, plus the 3 required secrets pull-secret, aws-creds, ssh-key). Maybe is recommended to separate them, or it is irrelevant? Maybe it is useful having them separately for day-2 operations?

**Comment by dgoodwin** [comment]
Hive must work with many versions of the installer over time, one of the major changes in v1 is to separate ClusterDeployment (info Hive needs) from he InstallConfig (info the openshift-install needs). It becomes quite complicated to parse multiple versions of the same object in go code, as such our current decision is to *not* parse InstallConfig in Hive code. This implies a couple small pieces of data are duplicated between the two.

In V1 API MachinePool objects are broken out into their own CRD, they can no longer be embedded within ClusterDeployment. ClusterImageSet has always been separate, although there is an override available on in the ClusterDeployment.Spec.Provisioning struct if you need it. You can however create all of these resources in one yaml file if desired.

**Comment by slopezz** [comment]
Thanks for clarification @dgoodwin!

So if I understood it correctly:
* I need always to create initially the base64 `install-config.yaml` for initial purpose (used on cluster creation time by the installer).
* On` ClusterDeployment` object I need to specify the same `baseDomain` already specified on  `install-config.yaml`
* In addition, initially `MachinePool` object need to coincide with workers spec defined on base64 initial `install-config.yaml`, but after the first installation succeeds, I guess this `MachinePool` object can be used on day-2 operations to manage the workers configuration in the future

Am I right?

**Comment by dgoodwin** [comment]
Looks correct, the pool in the InstallConfig is what the installer will create and the MachinePool is what will start being reconciled day 2, they may be different in some ways and you can have additional MachinePools in Hive that will show up once cluster is provisioned.

**Comment by staebler** [comment]
I'll also point out that you do not **need** to create the MachinePools. You only need them if you want Hive to manage the machines as part of day-2-to do scaling, labeling, or tainting.

**Comment by slopezz** [comment]
Thanks @dgoodwin @staebler. I have successfully deployed a 4.3.0 OCP cluster (clustername `hive-test-43`) using hive. Initially I had an error because I didn't specified the `iops` field (master/worker rootVolume), but I checked it was a required field (I don't know if it is really required but it is really not used, so just in case I calculated it by following  rule `size X GB * 3 =  Y iops`).

I have also managed successfully the `MachinePool` (in order to manage cluster size centrally from hive).

I was also thinking about other possible interesting day-2 operations, and I saw the `SyncIdentityProvider` object. I wanted to add a GitHub IDP like the following:

```
apiVersion: hive.openshift.io/v1
kind: SyncIdentityProvider
metadata:
  name: github-oauth-client-hive-test-43
spec:
  identityProviders:
  - github:
      clientID: XX..Github-oauth-cliend-id..XX
      clientSecret:
        name: github-oauth-client-hive-test-43
      teams:
      - XX..GitHub-Team..XX
    mappingMethod: claim
    name: github
    type: GitHub
  clusterDeploymentRefs:
  - name: "hive-test-43"
```

And so I created the `Secret` that github idp expects on `hive` namespace also:
```
kind: Secret
apiVersion: v1
metadata:
  name: github-oauth-client-hive-test-43
stringData:
  clientSecret: XX..Github-oauth-secret..XX
type: Opaque
```

Hive correctly configured the cluster `Oauth` object on target cluster `hive-test-43`:
```
hive-test-43
piVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    release.openshift.io/create-only: 'true'
spec:
  identityProviders:
    - github:
        ca:
          name: ''
        clientID: XX..Github-oauth-cliend-id..XX
        clientSecret:
          name: github-oauth-client-hive-test-43
        hostname: ''
        teams:
          - XX..GitHub-Team..XX
      mappingMethod: claim
      name: github
      type: GitHub
```
But referenced `Secret` `github-oauth-client-hive-test-43` was not created. It is expected to be manually created on target cluster, namespace `openshift-config`? Or can be created using hive as well?

Is there any other interesting day-2 operation (a part from managing possible `MachinePool` and `SyncIdentityProvider` objects?
