### ISSUE TITLE
When using MachinePool for day-2 ops hive ignore AZs on install-config

### ISSUE THREAD

**Issue by slopezz** [openshift/hive#842]
We are using hive in order to provision dev clusters on demmand, specifically:
- branch: `master`
- commit: `f95446d21ae47da6689f8de91c9b1463955223b7`

We are working with Openshift 4.3, and we want to use our pre-existing VPC (meeting all requirements on https://docs.openshift.com/container-platform/4.3/installing/installing_aws/installing-aws-vpc.html#installation-custom-aws-vpc-requirements_installing-aws-vpc).

Our created OCP 4.3 clusters work well without issues, but `MachinePool` objects does not work as expected (**hive ignores AZs specified on install-config.yaml, assuming that always it will be used all possible AZs per Region**).

Our specific VPC on us-east-1 region (N.Virginia can have up to 6 possible AZs), has only 3 AZs, so we specify on install-config.yaml:
- That masters/workers can be on us-east-1a, us-east-1b and us-east-1c
- 3 public subnets (a, b, c) and 3 private subnets (a, b, c)

### install-config.yaml
```yaml
$ cat dev-eng-ocp4-3-install-config.yaml
kind: Secret
apiVersion: v1
metadata:
  name: dev-eng-ocp4-3-install-config
  namespace: hive
type: Opaque
stringData:
  install-config.yaml: |
    apiVersion: v1
    baseDomain: domain.net
    compute:
    - name: worker
      platform:
        aws:
          rootVolume:
            iops: 150
            size: 50
            type: gp2
          type: m4.xlarge
          zones:
          - us-east-1a
          - us-east-1b
          - us-east-1c
      replicas: 3
    controlPlane:
      name: master
      platform:
        aws:
          rootVolume:
            iops: 150
            size: 50
            type: gp2
          type: m4.xlarge
          zones:
          - us-east-1a
          - us-east-1b
          - us-east-1c
      replicas: 1
    metadata:
      name: dev-eng-ocp4-3
    networking:
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineCIDR: 10.96.0.0/16
      networkType: OpenShiftSDN
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      aws:
        region: us-east-1
        subnets:
        - subnet-025758907adf90635
        - subnet-0e0fb00858d260850
        - subnet-009ea61fe23333552
        - subnet-0ef69f3be29aeeac7
        - subnet-0d87929b61d3d92b1
        - subnet-0cf2a66aef70f7abb
    pullSecret: ""
    sshKey: ssh-rsa A...@redhat.com
```

### ClusterDeployment
```yaml
$ cat dev-eng-ocp4-3-clusterdeployment.yaml 
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: dev-eng-ocp4-3
  namespace: hive
spec:
  baseDomain: domain.com
  clusterName: dev-eng-ocp4-3
  controlPlaneConfig:
    servingCertificates: {}
  installed: false
  platform:
    aws:
      credentialsSecretRef:
        name: dev-aws-hive-admin-user
      region: us-east-1
  provisioning:
    imageSetRef:
      name: ocp4-3-1
    installConfigSecretRef:
      name: dev-eng-ocp4-3-install-config
    sshPrivateKeySecretRef:
      name: ssh-keypair
  pullSecretRef:
    name: openshift-pull-secret
```

* We create the cluster, and it creates 3 MachineSets (because we just use 3 AZs, so it os OK):
![image](https://user-images.githubusercontent.com/41513123/75059298-f816bf00-54dc-11ea-9038-6063a5f58657.png)

* Then, as day-2 operation we want to manage workers nodes with `MachinePool`, so we increase workers nodes from 3 to 4:

```yaml
$ cat dev-eng-ocp4-3-machinepool.yaml 
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: dev-eng-ocp4-3-worker
  namespace: hive
spec:
  clusterDeploymentRef:
    name: dev-eng-ocp4-3
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 150
        size: 50
        type: gp2
      type: m4.xlarge
  replicas: 4
```

* The expected behaviour should be that hive updates one of the 3 existing machineSets on target cluster

* **However on `hiveadmission` pod logs it can be seen that its create 3 additional MachineSets on AZ d, e ,f (where there are no subnets, will never work):**
```
time="2020-02-21T17:43:11Z" level=info msg="reconciling machine pool" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="reconcile complete" controller=remotemachineset elapsed=10.615634ms machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="reconciling machine pool" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="reconciling machine pool for cluster deployment" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="found 3 remote machine sets" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="generated 6 worker machine sets" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="creating machineset" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker machineset=dev-eng-ocp4-3-4sdzp-worker-us-east-1d namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="creating machineset" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker machineset=dev-eng-ocp4-3-4sdzp-worker-us-east-1e namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="creating machineset" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker machineset=dev-eng-ocp4-3-4sdzp-worker-us-east-1f namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="updating machineset" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker machineset=dev-eng-ocp4-3-4sdzp-worker-us-east-1a namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="updating machineset" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker machineset=dev-eng-ocp4-3-4sdzp-worker-us-east-1b namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="updating machineset" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker machineset=dev-eng-ocp4-3-4sdzp-worker-us-east-1c namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="done reconciling machine sets for machine pool" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="found 0 remote machine autoscalers" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="done reconciling machine autoscalers for cluster deployment" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="reconcile complete" controller=remotemachineset elapsed=148.784891ms machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="reconciling machine pool" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="reconciling machine pool for cluster deployment" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:11Z" level=info msg="found 6 remote machine sets" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:12Z" level=info msg="generated 6 worker machine sets" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:12Z" level=info msg="done reconciling machine sets for machine pool" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:12Z" level=info msg="found 0 remote machine autoscalers" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:12Z" level=info msg="done reconciling machine autoscalers for cluster deployment" controller=remotemachineset machinePool=dev-eng-ocp4-3-worker namespace=hive
time="2020-02-21T17:43:12Z" level=info msg="reconcile complete" controller=remotemachineset elapsed=71.241718ms machinePool=dev-eng-ocp4-3-worker namespace=hive
```

* This can be seen also at target cluster on `openshift-machine-api` pod logs:
```
I0221 17:43:11.904621 1 controller.go:304] MachineSet "dev-eng-ocp4-3-4sdzp-worker-us-east-1d" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster 
I0221 17:43:11.904681 1 controller.go:331] Too few replicas for machine.openshift.io/v1beta1, Kind=MachineSet openshift-machine-api/dev-eng-ocp4-3-4sdzp-worker-us-east-1d, need 1, creating 1 I0221 17:43:11.904693 1 controller.go:337] Creating machine 1 of 1, ( spec.replicas(1) > currentMachineCount(0) ) 
I0221 17:43:12.079050 1 controller.go:304] MachineSet "dev-eng-ocp4-3-4sdzp-worker-us-east-1e" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster 
I0221 17:43:12.086921 1 controller.go:304] MachineSet "dev-eng-ocp4-3-4sdzp-worker-us-east-1f" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster 
I0221 17:43:12.092757 1 controller.go:304] MachineSet "dev-eng-ocp4-3-4sdzp-worker-us-east-1a" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster 
I0221 17:43:12.092913 1 controller.go:304] MachineSet "dev-eng-ocp4-3-4sdzp-worker-us-east-1b" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster 
I0221 17:43:12.093084 1 controller.go:304] MachineSet "dev-eng-ocp4-3-4sdzp-worker-us-east-1c" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster 
I0221 17:43:12.093215 1 controller.go:304] MachineSet "dev-eng-ocp4-3-4sdzp-worker-us-east-1d" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster 
I0221 17:43:12.097784 1 controller.go:304] MachineSet "dev-eng-ocp4-3-4sdzp-worker-us-east-1e" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster 
I0221 17:43:12.097946 1 controller.go:304] MachineSet "dev-eng-ocp4-3-4sdzp-worker-us-east-1f" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster 
I0221 17:43:12.098499 1 controller.go:304] MachineSet "dev-eng-ocp4-3-4sdzp-worker-us-east-1d" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster 
I0221 17:43:12.406567 1 controller.go:304] MachineSet "dev-eng-ocp4-3-4sdzp-worker-us-east-1d" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster 
I0221 17:43:12.412749 1 controller.go:304] MachineSet "dev-eng-ocp4-3-4sdzp-worker-us-east-1d" in namespace "openshift-machine-api" doesn't specify "cluster.k8s.io/cluster-name" label, assuming nil cluster 
```
* And the image of the 3 extra machineSets on AZ d, e ,f, one of them (d) has 0/1 nodes (which is normal because there are no subnets, it will never work).
![image](https://user-images.githubusercontent.com/41513123/75058427-46c35980-54db-11ea-892b-8e40748a7c63.png)

* In addition it can be seen that from hive point of view, there are 4 replicas (but actually 3):
```
$ kubectl describe machinepool dev-eng-ocp4-3-worker
Name:         dev-eng-ocp4-3-worker
Namespace:    hive
...
Spec:
  Cluster Deployment Ref:
    Name:  dev-eng-ocp4-3
  Name:    worker
  Platform:
    Aws:
      Root Volume:
        Iops:  150
        Size:  50
        Type:  gp2
      Type:    m4.xlarge
  Replicas:    4
Status:
  Machine Sets:
    Max Replicas:  1
    Min Replicas:  1
    Name:          dev-eng-ocp4-3-4sdzp-worker-us-east-1a
    Replicas:      1
    Max Replicas:  1
    Min Replicas:  1
    Name:          dev-eng-ocp4-3-4sdzp-worker-us-east-1b
    Replicas:      1
    Max Replicas:  1
    Min Replicas:  1
    Name:          dev-eng-ocp4-3-4sdzp-worker-us-east-1c
    Replicas:      1
    Max Replicas:  1
    Min Replicas:  1
    Name:          dev-eng-ocp4-3-4sdzp-worker-us-east-1d
    Replicas:      1
    Max Replicas:  0
    Min Replicas:  0
    Name:          dev-eng-ocp4-3-4sdzp-worker-us-east-1e
    Replicas:      0
    Max Replicas:  0
    Min Replicas:  0
    Name:          dev-eng-ocp4-3-4sdzp-worker-us-east-1f
    Replicas:      0
  Replicas:        4
Events:            <none>
```
* From my point of view, it you specify specific AZs on install-config (that can be less than possible AZs on a given AWS region), hive shouldn't assume that can use all possible AZs on each Region,  ignoring  what is specified on install-config file
