### ISSUE TITLE
Problem with MachinePools in cluster installed in existing VPC

### ISSUE THREAD

**Issue by roivaz** [openshift/hive#886]
We are using hive to create and manage ocp clusters in AWS. In some cases we are using the option to install the cluster in an already existent VPC, but we have found a problem with MachinePools in this scenario:

* When a new MachinePool is created, hive creates the proper MachineSets in the ocp cluster, but it does so by specifying the `spec.providerSpec.subnet` field like this:

```yaml
securityGroups:
  - filters:
      - name: tag:Name
        values:
          - stg-saas-ocp4-3-skbkh-worker-sg
```

* This is is problematic because our subnets, that are created before the cluster is, don't have the `Name` tag that this configuration is expectig, thus causing the Machine objects to get into failed state.

As far as I was able to check, there is no way to specify the subnet IDs to be used in the MachinePool, but I migh have overlooked something. Is it possible?
If not, will this be supported at some point?

For the moment, we are going to try to use SyncSets to manage our MachineSets in the case of clusters provisioned in already existent VPCs. Do you think there could be problems with this approach?

This is the MachinePool configuration we were trying to use and that resulted in the problem described:

```yaml
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: stg-saas-ocp4-3-worker-m5-2xlarge
  namespace: hive
spec:
  clusterDeploymentRef:
    name: stg-saas-ocp4-3
  name: worker-m5-2xlarge
  platform:
    aws:
      rootVolume:
        iops: 150
        size: 50
        type: gp2
      type: m5.2xlarge
      zones:
      - us-east-1a
      - us-east-1b
      - us-east-1c
  replicas: 3
```
